name: 'marketing_attribution'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]

models:
  marketing_attribution:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics